repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: local
  hooks: 
  - id: build-themes
    name: build themes
    language: system
    entry: npm run build
    files: ^src/.*\.json$