import { Palette } from '../palette'
import { opacity } from '../utils'

export const getColors = (): Record<string, unknown> => {
  return {
    'editor.background': Palette.back,
    'editorCursor.foreground': Palette.text,
    'editor.foreground': Palette.text,
    'editorWhitespace.foreground': Palette.overlay,
    'editor.lineHighlightBackground': Palette.highlight_low,
    'editor.selectionBackground': Palette.highlight_high,
    'editor.inactiveSelectionBackground': Palette.highlight_med,
    'editor.selectionHighlightBackground': Palette.highlight_med,
    'editorLineNumber.foreground': Palette.accent4,
    'editorLineNumber.activeForeground': Palette.subtle,
    'editor.wordHighlightBackground': Palette.highlight_med,
    // UI Colors
    foreground: Palette.text,
    'textLink.foreground': Palette.accent1,
    'activityBar.background': Palette.ui,
    'activityBar.foreground': Palette.accent3,
    'sideBar.background': Palette.ui,
    'statusBar.background': Palette.ui,
    'statusBar.debuggingBackground': Palette.accent4,
    'statusBarItem.remoteBackground': Palette.accent5,
    'titleBar.activeBackground': Palette.ui,
    'titleBar.inactiveBackground': Palette.ui,
    'tab.activeBackground': Palette.overlay,
    'tab.inactiveBackground': Palette.ui,
    'tab.border': Palette.back,
    'tab.activeBorder': Palette.accent4,
    // Editor gutter
    'editorGutter.modifiedBackground': Palette.accent3,
    'editorGutter.addedBackground': Palette.accent4,
    'editorGutter.deletedBackground': Palette.accent6,
    'editorGutter.foldingControlForeground': Palette.accent2,
    // Git Colors
    'gitDecoration.addedResourceForeground': Palette.accent4,
    'gitDecoration.modifiedResourceForeground': Palette.accent3,
    'gitDecoration.deletedResourceForeground': Palette.accent6,
    'gitDecoration.renamedResourceForeground': Palette.accent4,
    'gitDecoration.stageModifiedResourceForeground': Palette.accent4,
    'gitDecoration.stageDeletedResourceForeground': Palette.accent4,
    'gitDecoration.untrackedResourceForeground': Palette.subtle,
    'gitDecoration.ignoredResourceForeground': Palette.muted,
    'gitDecoration.conflictingResourceForeground': Palette.accent5,
    'editorGroupHeader.noTabsBackground': Palette.ui,
    'editorGroupHeader.tabsBackground': Palette.back,
    'progressBar.background': Palette.accent1,
    // Minimap Colors
    'minimap.findMatchHighlight': Palette.accent3,
    'minimap.selectionHighlight': Palette.highlight_high,
    'minimap.errorHighlight': Palette.accent6,
    'minimap.warningHighlight': Palette.accent5,
    'minimap.selectionOccurrenceHighlight': Palette.highlight_med,
    'minimapGutter.addedBackground': Palette.accent4,
    'minimapGutter.modifiedBackground': Palette.accent3,
    'minimapGutter.deletedBackground': Palette.accent6,
    // Breadcrumb Colors
    'breadcrumb.foreground': Palette.text,
    'breadcrumb.focusForeground': Palette.subtle,
    'breadcrumb.activeSelectionForeground': Palette.subtle,
    'breadcrumbPicker.background': Palette.ui,
    // Diff Colors
    'diffEditor.insertedTextBackground': opacity(Palette.accent4, 0.5),
    'diffEditor.insertedLineBackground': opacity(Palette.accent4, 0.4),
    'diffEditorGutter.insertedLineBackground': opacity(Palette.accent4, 0.4),
    'diffEditorOverview.insertedForeground': Palette.accent4,
    'diffEditor.removedTextBackground': opacity(Palette.accent6, 0.5),
    'diffEditor.removedLineBackground': opacity(Palette.accent6, 0.4),
    'diffEditorGutter.removedLineBackground': opacity(Palette.accent6, 0.4),
    'diffEditorOverview.removedForeground': Palette.accent6,
    'diffEditor.diagonalFill': Palette.overlay,
    // Merge conflict Colors
    'merge.currentHeaderBackground': opacity(Palette.accent1, 0.56),
    'merge.currentContentBackground': opacity(Palette.accent1, 0.37),
    'editorOverviewRuler.currentContentForeground': opacity(Palette.accent1, 0.56),
    'merge.incomingHeaderBackground': opacity(Palette.accent5, 56),
    'merge.incomingContentBackground': opacity(Palette.accent5, 0.37),
    'editorOverviewRuler.incomingContentForeground': opacity(Palette.accent5, 0.56),
    // Testing Colors
    'testing.iconFailed': Palette.accent6,
    'testing.iconErrored': Palette.accent6,
    'testing.iconPassed': Palette.accent4,
    'testing.runAction': Palette.accent2,
    'testing.iconQueued': Palette.subtle,
    'testing.iconUnset': Palette.muted,
    'testing.iconSkipped': Palette.accent3,
    'testing.peekBorder': Palette.accent6,
    'testing.peekHeaderBackground': opacity(Palette.accent6, 0.6),
    'testing.message.error.decorationForeground': Palette.accent6,
    // Debug Colors
    'debugIcon.breakpointForeground': Palette.accent6,
    'debugIcon.breakpointDisabledForeground': Palette.muted,
    'debugIcon.breakpointCurrentStackframeForeground': Palette.accent1,
    'debugIcon.startForeground': Palette.accent1,
    'debugIcon.pauseForeground': Palette.accent3,
    'debugIcon.stopForeground': Palette.accent6,
    'debugIcon.disconnectForeground': Palette.accent6,
    'debugIcon.restartForeground': Palette.accent4,
    'debugIcon.stepOverForeground': Palette.accent3,
    'debugIcon.stepIntoForeground': Palette.accent3,
    'debugIcon.stepOutForeground': Palette.accent5,
    'debugIcon.continueForeground': Palette.accent1,
    'debugIcon.stepBackForeground': Palette.accent3,
    'debugConsole.infoForeground': Palette.accent2,
    'debugConsole.warningForeground': Palette.accent3,
    'debugConsole.errorForeground': Palette.accent5,
    'debugConsole.sourceForeground': Palette.accent5,
    'debugConsoleInputIcon.foreground': Palette.accent1,
    // Inlay Hint Colors
    'editor.inlineSuggest.enabled': true,
    'editorInlayHint.background': Palette.ui,
    'editorInlayHint.foreground': Palette.subtle
  }
}
