import { Palette } from "../palette"
import { opacity } from "../utils"

export const getColors = () => {
    return {
		"editor.background": Palette.back,
		"editorCursor.foreground": Palette.text,
		"editor.foreground": Palette.text,
		"editorWhitespace.foreground": Palette.overlay,
		"editor.lineHighlightBackground": Palette.highlight_low,
		"editor.selectionBackground": Palette.highlight_high,
		"editor.inactiveSelectionBackground": Palette.highlight_med,
		"editor.selectionHighlightBackground": Palette.highlight_med,
		"editorLineNumber.foreground": Palette.green,
		"editorLineNumber.activeForeground": Palette.subtle,
		"editor.wordHighlightBackground": Palette.highlight_med,
		// UI Colors
		"foreground": Palette.text,
		"textLink.foreground": Palette.pink,
		"activityBar.background": Palette.ui,
		"activityBar.foreground": Palette.camel,
		"sideBar.background": Palette.ui,
		"statusBar.background": Palette.ui,
		"statusBar.debuggingBackground": Palette.green,
		"statusBarItem.remoteBackground": Palette.purple,
		"titleBar.activeBackground": Palette.ui,
		"titleBar.inactiveBackground": Palette.ui,
		"tab.activeBackground": Palette.overlay,
		"tab.inactiveBackground": Palette.ui,
		"tab.border": Palette.back,
		"tab.activeBorder": Palette.green,
		// Editor gutter
		"editorGutter.modifiedBackground": Palette.camel,
		"editorGutter.addedBackground": Palette.green,
		"editorGutter.deletedBackground": Palette.red,
		"editorGutter.foldingControlForeground": Palette.blue,
		// Git Colors
		"gitDecoration.addedResourceForeground": Palette.green,
		"gitDecoration.modifiedResourceForeground": Palette.camel,
		"gitDecoration.deletedResourceForeground": Palette.red,
		"gitDecoration.renamedResourceForeground": Palette.green,
		"gitDecoration.stageModifiedResourceForeground": Palette.green,
		"gitDecoration.stageDeletedResourceForeground": Palette.green,
		"gitDecoration.untrackedResourceForeground": Palette.subtle,
		"gitDecoration.ignoredResourceForeground": Palette.muted,
		"gitDecoration.conflictingResourceForeground": Palette.purple,
		"editorGroupHeader.noTabsBackground": Palette.ui,
		"editorGroupHeader.tabsBackground": Palette.back,
		"progressBar.background": Palette.pink,
		// Minimap Colors
		"minimap.findMatchHighlight": Palette.camel,
		"minimap.selectionHighlight": Palette.highlight_high,
		"minimap.errorHighlight": Palette.red,
		"minimap.warningHighlight": Palette.purple,
		"minimap.selectionOccurrenceHighlight": Palette.highlight_med,
		"minimapGutter.addedBackground": Palette.green,
		"minimapGutter.modifiedBackground": Palette.camel,
		"minimapGutter.deletedBackground": Palette.red,
		// Breadcrumb Colors
		"breadcrumb.foreground": Palette.text,
		"breadcrumb.focusForeground": Palette.subtle,
		"breadcrumb.activeSelectionForeground": Palette.subtle,
		"breadcrumbPicker.background": Palette.ui,
		// Diff Colors
		"diffEditor.insertedTextBackground": opacity(Palette.green, 0.5),
		"diffEditor.insertedLineBackground": opacity(Palette.green, 0.4),
		"diffEditorGutter.insertedLineBackground": opacity(Palette.green, 0.4),
		"diffEditorOverview.insertedForeground": Palette.green,
		"diffEditor.removedTextBackground": opacity(Palette.red, 0.5),
		"diffEditor.removedLineBackground": opacity(Palette.red, 0.4),
		"diffEditorGutter.removedLineBackground": opacity(Palette.red, 0.4),
		"diffEditorOverview.removedForeground": Palette.red,
		"diffEditor.diagonalFill": Palette.overlay,
		// Merge conflict Colors
		"merge.currentHeaderBackground": opacity(Palette.pink, 0.56),
		"merge.currentContentBackground": opacity(Palette.pink, 0.37),
		"editorOverviewRuler.currentContentForeground": opacity(Palette.pink, 0.56),
		"merge.incomingHeaderBackground": opacity(Palette.purple, 56),
		"merge.incomingContentBackground": opacity(Palette.purple, 0.37),
		"editorOverviewRuler.incomingContentForeground": opacity(Palette.purple, 0.56),
		// Testing Colors
		"testing.iconFailed": Palette.red,
		"testing.iconErrored": Palette.red,
		"testing.iconPassed": Palette.green,
		"testing.runAction": Palette.blue,
		"testing.iconQueued": Palette.subtle,
		"testing.iconUnset": Palette.muted,
		"testing.iconSkipped": Palette.camel,
		"testing.peekBorder": Palette.red,
		"testing.peekHeaderBackground": opacity(Palette.red, 0.6),
		"testing.message.error.decorationForeground": Palette.red,
		// Debug Colors
		"debugIcon.breakpointForeground": Palette.red,
		"debugIcon.breakpointDisabledForeground": Palette.muted,
		"debugIcon.breakpointCurrentStackframeForeground": Palette.pink,
		"debugIcon.startForeground": Palette.pink,
		"debugIcon.pauseForeground": Palette.camel,
		"debugIcon.stopForeground": Palette.red,
		"debugIcon.disconnectForeground": Palette.red,
		"debugIcon.restartForeground": Palette.green,
		"debugIcon.stepOverForeground": Palette.camel,
		"debugIcon.stepIntoForeground": Palette.camel,
		"debugIcon.stepOutForeground": Palette.purple,
		"debugIcon.continueForeground": Palette.pink,
		"debugIcon.stepBackForeground": Palette.camel,
		"debugConsole.infoForeground": Palette.blue,
		"debugConsole.warningForeground": Palette.camel,
		"debugConsole.errorForeground": Palette.purple,
		"debugConsole.sourceForeground": Palette.purple,
		"debugConsoleInputIcon.foreground": Palette.pink
    }
}
